// <auto-generated />
using ControleDeEstoqueApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeEstoqueApi.Migrations
{
    [DbContext(typeof(DbConnection))]
    partial class DbConnectionModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ControleDeEstoqueApi.Domain.Models.Estoque", b =>
                {
                    b.Property<int>("id_estoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cod_func")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cod_prod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome_fab")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nome_fant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nome_prod")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("id_estoque");

                    b.ToTable("estoque");
                });

            modelBuilder.Entity("ControleDeEstoqueApi.Domain.Models.Item_Venda", b =>
                {
                    b.Property<int>("id_item_venda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cod_func")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cod_prod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cod_venda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("codigo_item_venda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("valor_unitario")
                        .HasColumnType("TEXT");

                    b.HasKey("id_item_venda");

                    b.HasIndex("codigo_item_venda")
                        .IsUnique();

                    b.ToTable("item_venda");
                });

            modelBuilder.Entity("ControleDeEstoqueApi.Domain.Models.Pagamento", b =>
                {
                    b.Property<int>("id_pagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome_pagmt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id_pagamento");

                    b.HasIndex("nome_pagmt")
                        .IsUnique();

                    b.ToTable("pagamento");
                });

            modelBuilder.Entity("ControleDeEstoqueApi.Domain.Models.Produto", b =>
                {
                    b.Property<int>("id_produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cod_fab")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cod_fornc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cod_prod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("nome_prod")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("quantidade_min")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("valor_compra")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("valor_venda")
                        .HasColumnType("TEXT");

                    b.HasKey("id_produto");

                    b.HasIndex("cod_prod")
                        .IsUnique();

                    b.ToTable("produto");
                });
#pragma warning restore 612, 618
        }
    }
}
